### ISSUE TITLE
Dependency to lodash.pick ?

### ISSUE THREAD

**Issue by lenybernard** [RealFaviconGenerator/cli-real-favicon#10]
Hi,

While playing with this awesome generator (🎖 btw), I'm not able to run it without a hack.
First here is my package.json (I use yarn but nevermind I suppose):
```json
{
  "name": "myPackageName",
  ...
  "dependencies": {
    "cli-real-favicon": "^0.0.6"
  }
}
```
When I run the command and try to generate favicons, I've got this:
```
module.js:457
    throw err;
    ^

Error: Cannot find module 'lodash.pick'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    ...
```

Is it something I misenderstood or should `cli-real-favicon` should require lodash.pick ?

When I add this line in my package json, it does work properly and I get the `Generation completed` message I expect :
```diff

  "dependencies": {
    "cli-real-favicon": "^0.0.6",
+   "lodash.pick": "^4.2.1"
  }
```

**Comment by phbernard** [comment]
Hi,

`lodash.pick` is an indirect dependency of `cli-real-favicon`. The freshly generated `package-lock.json` might help understanding what is going on.
