### ISSUE TITLE
Globbing doesn't work under windows

### ISSUE THREAD

**Issue by dbartholomae** [RealFaviconGenerator/cli-real-favicon#2]
Hi there! :)

Currently globbing for `real-favicon inject` does not work under windows. It would be great to add globbing e.g. via https://www.npmjs.com/package/glob to make it work.
Would a pull request be welcomed?

Best,
Daniel

**Comment by phbernard** [comment]
Hi Daniel,

Thank you for your feedback. Sure, a PR would certainly be welcome!!

Cheers,
Philippe

**Comment by dbartholomae** [comment]
Sure, no problem! I would need to wrap the code in two more functions (one expanding each glob pattern, the other one to iterate over each expanded file).
To avoid callback hell I usually would opt for promises in this case. Would a rewrite using promises be fine for you?

**Comment by phbernard** [comment]
Yep, sounds good to me!

**Comment by dbartholomae** [comment]
Here you are #3

**Comment by phbernard** [comment]
Thank you again! Your change is part of v0.0.5, published a minute ago.
