### ISSUE TITLE
allow use as module as well as cli

### ISSUE THREAD

**Issue by ismay** [RealFaviconGenerator/cli-real-favicon#4]
It would be nice if real-favicon could be used as a module, as well as a cli. That way it can be included in larger apps without touching the command line.

**Comment by phbernard** [comment]
https://github.com/RealFaviconGenerator/rfg-api maybe? :)

**Comment by ismay** [comment]
Doh 🙈. Ok thx!

**Comment by phbernard** [comment]
... and sorry for this very late answer :(

**Comment by ismay** [comment]
No problem :), thanks for the reply!
